samples:
  fathers_pool:
    resolution: 10
    universe: "[0.0,1.0]"
  mothers_pool:
    resolution: 10
    universe: "[0.0,1.0]"

events:
  fathers_only:        "fathers_pool:]0.0,1.0] & mothers_pool:0.0"
  mothers_only:        "mothers_pool:]0.0,1.0] & fathers_pool:0.0"
  fathers_and_mothers: "fathers_pool:]0.0,1.0] & mothers_pool:]0.0,1.0]"
  
